name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose test environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - production

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Set Environment Variable
        run: echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Check Project Structure
        run: ls -R

      - name: Install Dependencies
        run: |
          cd $(find . -name "pom.xml" -exec dirname {} \;)
          mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: |
          cd $(find . -name "pom.xml" -exec dirname {} \;)
          mvn test
