name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # تشغيل يدوي عند الحاجة

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test
